name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs['crates/fijit--release_created'] }}
      tag_name: ${{ steps.release.outputs['crates/fijit--tag_name'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release

  build:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      tag: ${{ needs.release-please.outputs.tag_name }}
